services:
  keycloak: # https://hub.docker.com/r/bitnami/keycloak
    container_name: keycloak-theme
    image: bitnami/keycloak:21.1.2
    volumes:
      - ./keycloak-theme:/opt/bitnami/keycloak/themes/blackmoon
    ports:
      - "18081:8080"
    environment:
      KEYCLOAK_HTTP_RELATIVE_PATH: /auth
      KEYCLOAK_DATABASE_HOST: postgres
      KEYCLOAK_DATABASE_PASSWORD: "#3]O?4RGj)DE7Z!9SA5"
      KEYCLOAK_ADMIN_USER: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    restart: on-failure
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/auth"]
      interval: 30s
      timeout: 15s
      retries: 5
      start_period: 30s
  postgres: # https://hub.docker.com/_/postgres
    container_name: postgres-keycloak-theme
    image: postgres:14.5-alpine
    environment:
      POSTGRES_DB: bitnami_keycloak
      POSTGRES_USER: bn_keycloak
      POSTGRES_PASSWORD: "#3]O?4RGj)DE7Z!9SA5"
    restart: on-failure
    volumes:
      - postgres:/var/lib/postgresql/data
volumes:
  postgres:
    driver: local
